---
sudo: false
language: ruby
cache: bundler
bundler_args: --without acceptance_testing metatools
env:
- PUPPET_GEM_VERSION='4.0.0' STRICT_VARIABLES='yes'
- PUPPET_GEM_VERSION='~> 4.0' STRICT_VARIABLES='yes'
- PUPPET_GEM_VERSION='5.0.0'
- PUPPET_GEM_VERSION='~> 5.0'
rvm:
- 2.3.5
- 2.4.2
- 2.5.0
matrix:
  exclude:
  - rvm: 2.4.2
    env: PUPPET_GEM_VERSION='4.0.0' STRICT_VARIABLES='yes'
  - rvm: 2.5.0
    env: PUPPET_GEM_VERSION='4.0.0' STRICT_VARIABLES='yes'
script: bundle exec rake travis:ci
after_script: bundle exec codeclimate-test-reporter
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/3402fe31d5b814c57316
    on_success: always
    on_failure: always
    on_start: never
